name: Node.js CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          echo "${{ secrets.ENVIRONMENT }}" > .env
      - run: npm ci
      # - run: npm test
      - run: npm run build
      - run: pm2 restart nodepop


sudo apt update
sudo apt install nginx

sudo systemctl status nginx

sudo nano etc/nginx/sites-available/cicd

  GNU nano 6.2                                                              /etc/nginx/sites-available/cicd
server {
        listen 80;

        location / {

          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;

        }

}

sudo nginx -t

sudo systemctl reload nginx

sudo ln -s /etc/nginx/sites-available/cicd /etc/nginx/sites-enabled

sudo rm /etc/nginx/sites-enabled/default

sudo nano /etc/nginx/sites-available/cicd


server {
        listen 80;
        server_name keepcodingcicd.duckdns.org;

        location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        }


}


 sudo apt install certbot python3-certbot-nginx

 sudo certbot --nginx